### ISSUE TITLE
user-can-retrieve-trivia-data.md

### ISSUE THREAD

**Issue by damien-martinez** [damien-martinez/trivia-game#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

App will retrieve data for trivia questions based on user preferences.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to retrieve a set of trivia questions based on preferences.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="491" alt="Screen Shot 2022-03-01 at 10 30 33 AM" src="https://user-images.githubusercontent.com/40590740/156227730-1fb30fb1-dd8b-4586-a041-6e6aa220abbf.png">
<img width="213" alt="Screen Shot 2022-03-01 at 10 30 44 AM" src="https://user-images.githubusercontent.com/40590740/156227760-2285e61c-03c2-4d61-b7ef-f70b8b1db791.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Code HTML and CSS so that the page looks identical to the wireframe.
- [x] Create forms so that the user can set up the trivia game based on preferences.
- [x] Create a new XHR object so that trivia questions can be pulled from API when user clicks on "Get Trivia!" button.
- [x] Console log return value to see if data was pulled correctly. 
- [x] Look over everything to see if there are any bugs and errors
- [x] Fix all bugs and errors
