### ISSUE TITLE
Feature: User will have a time limit to answer a question. 

### ISSUE THREAD

**Issue by damien-martinez** [damien-martinez/trivia-game#13]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will have a time limit to answer a question. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to see a 30 second timer within the app. Once the time reaches 0 seconds, the user will be notified that the time is up, then the app will go to the next question.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-03-17 at 5 02 54 PM](https://user-images.githubusercontent.com/40590740/158912972-e249296f-3dc9-481a-92a0-16200514c066.png)

![Screen Shot 2022-03-17 at 4 53 44 PM](https://user-images.githubusercontent.com/40590740/158912991-7ae9cd55-43c2-4940-b9d5-4a0d42df2154.png)

![Screen Shot 2022-03-17 at 4 57 57 PM](https://user-images.githubusercontent.com/40590740/158913016-4b6548bb-b016-462d-ab2f-441f9e3d537d.png)

![Screen Shot 2022-03-17 at 4 59 30 PM](https://user-images.githubusercontent.com/40590740/158913040-27ca5099-63b5-4224-9612-d04db5eaaa33.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Add an element to the DOM that indicates how much time the user has left
- [ ] As each second goes by, update DOM to reflect
- [ ] Once time reaches 0 seconds, update DOM to show next question and reset time
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
