### ISSUE TITLE
user-can-answer-question-and-get-results.md

### ISSUE THREAD

**Issue by damien-martinez** [damien-martinez/trivia-game#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can answer a question and show a correct or incorrect answer

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When user chooses an answer and submits the answer, the app will tell them if they answered correct or incorrect. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="178" alt="Screen Shot 2022-03-01 at 11 02 00 AM" src="https://user-images.githubusercontent.com/40590740/156232252-0e30896a-87bc-4299-9720-fb236f36f4ed.png">
<img width="171" alt="Screen Shot 2022-03-01 at 11 02 05 AM" src="https://user-images.githubusercontent.com/40590740/156232272-85852ca7-7b82-4ce4-b051-c2f51e314371.png">
<img width="183" alt="Screen Shot 2022-03-01 at 11 02 10 AM" src="https://user-images.githubusercontent.com/40590740/156232293-315c1940-8fde-44b9-bd8c-5aa4f0c773c8.png">
<img width="382" alt="Screen Shot 2022-03-01 at 11 02 36 AM" src="https://user-images.githubusercontent.com/40590740/156232312-689ad30c-fe99-4cf8-8641-27285b98e499.png">
<img width="383" alt="Screen Shot 2022-03-01 at 11 02 44 AM" src="https://user-images.githubusercontent.com/40590740/156232326-468e87d9-11be-4fbf-9d21-6c0e6486054d.png">
<img width="377" alt="Screen Shot 2022-03-01 at 11 02 52 AM" src="https://user-images.githubusercontent.com/40590740/156232335-9f78014e-4ccf-4e43-8c3e-85c5cf17db7c.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Once a user clicks on 'Play Trivia!' button, create a DOM tree to show the question along with all of the possible answers
- [x] Change color of whatever answer they choose.
- [x] If answer is right, answer will flash green after submit button is clicked
- [x] If answer is wrong, answer will flash red after submit button is clicked
- [x] Run code and trigger listeners to see if the code is free of any bugs or errors
- [x] Fix all bugs and errors.
